services:
  mongodb:
    image: mongo
    container_name: securepass_mongodb
    command: mongod --bind_ip_all
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    healthcheck:
      test: mongosh --eval "db.adminCommand('ping')" -u ${MONGO_ROOT_USER} -p ${MONGO_ROOT_PASSWORD} --authenticationDatabase admin
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongodb_data:/data/db
    networks:
      - securepass_network

  backend:
    build: .
    container_name: securepass_backend
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - ./src:/app/src
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - securepass_network

volumes:
  mongodb_data:

networks:
  securepass_network:
    driver: bridge